# Yarn 4 Configuration

# Use node_modules (traditional) instead of Plug'n'Play for better compatibility
nodeLinker: node-modules

# Network resilience settings to handle intermittent 502 errors
httpTimeout: 300000
httpRetry: 10
networkConcurrency: 1

# Enable global cache to speed up installations
enableGlobalCache: true
